/**************************************************************************
* Project  : Actuarial Pricing Model (French MTPL)
*
* Phase    : 1
* Section  : 10
*
* Reporting
*
* Creates a complete PDF report of
*
*   • Exposure Analysis
*   • Offset Validation
*   • Claim Rate Analysis
*
**************************************************************************/

ods graphics on;

ods listing close;


/***********************************************************************
* Report Destination
***********************************************************************/

ods pdf

file="C:\REPORT\Phase1_Exposure_Analysis.pdf"

style=journal

notoc;


/***********************************************************************
* Report Title
***********************************************************************/

title1 j=center
"French MTPL Portfolio";

title2 j=center
"Phase 1";

title3 j=center
"Data Cleaning and Exposure Analysis";

footnote1
"Generated by SAS";


/***********************************************************************
* Section 1
***********************************************************************/

ods proclabel="Exposure Summary";

title2 "Exposure Summary";

proc means data=work.dat_final

n mean median std min q1 q3 max sum;

var Exposure;

run;


/***********************************************************************
* Section 2
***********************************************************************/

ods proclabel="Exposure Distribution";

title2 "Exposure Distribution";

proc sgplot
data=work.dat_final;

histogram Exposure;

density Exposure;

run;


/***********************************************************************
* Section 3
***********************************************************************/

ods proclabel="Exposure Boxplot";

title2 "Exposure Boxplot";

proc sgplot
data=work.dat_final;

vbox Exposure;

run;


/***********************************************************************
* Section 4
***********************************************************************/

ods proclabel="Recording Precision";

title2 "Recording Precision";

proc freq
data=work.exposure_precision;

tables RecordingPrecision;

run;


/***********************************************************************
* Section 5
***********************************************************************/

ods proclabel="Exposure versus Rating Factors";

title2 "Exposure by Area";

proc sgplot
data=work.dat_final;

vbox Exposure /
category=Area;

run;


title2 "Exposure by Fuel";

proc sgplot
data=work.dat_final;

vbox Exposure /
category=VehGas;

run;


title2 "Exposure by Vehicle Brand";

proc sgplot
data=work.dat_final;

vbox Exposure /
category=VehBrand;

run;


/***********************************************************************
* Section 6
***********************************************************************/

ods proclabel="Offset Validation";

title2 "Distribution of Log(Exposure)";

proc sgplot
data=work.dat_final;

histogram Log_Exposure;

density Log_Exposure;

run;


proc means
data=work.dat_final

n
mean
median
std
min
max;

var Log_Exposure;

run;


/***********************************************************************
* Section 7
***********************************************************************/

ods proclabel="Claim Rate";

title2 "Claim Rate Distribution";

proc sgplot
data=work.dat_claimrate;

histogram ClaimRate;

density ClaimRate;

run;


title2 "Claim Rate Summary";

proc means
data=work.dat_claimrate

n
mean
median
std
min
q1
q3
max;

var ClaimRate;

run;


/***********************************************************************
* Section 8
***********************************************************************/

ods proclabel="GLM Comparison";

title2 "Model Fit Statistics";

proc print
data=FitComparison
label;

run;


title2 "Parameter Estimates";

proc print
data=ParameterComparison
label;

run;


/***********************************************************************
* Closing Page
***********************************************************************/

title1 "Summary";

proc odstext;

p "Phase 1 completed successfully.";

p "Validated datasets:";

list;

item "WORK.DAT_FINAL";

item "WORK.EXPOSURE_PRECISION";

item "WORK.DAT_CLAIMRATE";

end;

p "These datasets are ready for";

list;

item "Phase 2 - Poisson GLM";

item "Phase 3 - Machine Learning";

item "Phase 4 - Explainable AI";

end;

run;


/***********************************************************************
* Close Report
***********************************************************************/

ods pdf close;

ods listing;

ods graphics off;

title;
footnote;
